version: 0.2

phases:
  build:
    commands:
      - echo "<br>Today's secret:<br>" >> index.html
      - echo "<br>" >> index.html
      - echo "$FAKE_VAR" >> index.html
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
      - rm buildspec.yml

artifacts:
  files:
    - '**/*'
  name: build_output
